name: ClairvoyanceMonad

on: [push, pull_request]

jobs:
  checking-coq:
    name: Building ClairvoyanceMonad
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        ocaml: [4.14.1]
        coq: [8.15.1, 8.16.1]
        include:
          - coq: 8.15.1
            equations: 1.3+8.15
          - coq: 8.16.1
            equations: 1.3+8.16
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Caching OPAM
        id: caching-opam
        uses: actions/cache@v2
        with:
          path: ~/.opam
          key: opam-${{ runner.os }}-coq${{ matrix.coq }}
      - name: Caching Local OPAM
        id: caching-local-opam
        uses: actions/cache@v2
        with:
          path: _opam
          key: coq-opam-${{ runner.os }}-coq${{ matrix.coq }}
      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml }}
          opam-disable-sandboxing: true
      - name: Set up Coq
        run: |
          opam init -j 2 -n -y || true
          opam repo add coq-released http://coq.inria.fr/opam/released || true
          opam update
          opam install -v -y -j 1 --unlock-base coq.${{ matrix.coq }}
          opam pin coq ${{ matrix.coq }}
          opam install -y coq-equations.${{ matrix.equations }}
      - name: Compiling Coq files
        run: |
          eval $(opam env)
          make
